// 上海新教材 7A Unit 1 "Trying new things" 词汇数据
// 字段说明：
//   id          序号
//   word        单词 / 词组
//   pos         词性
//   meaning     中文释义
//   section     教材出处（按页码分组）
//   derivatives 词性转换 [{ word, pos, meaning, example?: { en, cn } }]
//   usage       用法 / 搭配 [String]
//   example     例句 { en, cn }
//   synonyms / antonyms 近义 / 反义

const VOCAB = [
  // ===== P14-15 Viewing and Listening =====
  { id: 1, word: "a talk light", pos: "n. 短语", meaning: "一台会说话的灯", section: "P14-15 Viewing & Listening" },
  { id: 2, word: "try", pos: "v.", meaning: "尝试；努力",
    section: "P14-15 Viewing & Listening",
    derivatives: [{ word: "tried", pos: "v. 过去式/分词", meaning: "尝试（过去）" , example: { en: "We tried sushi for the first time yesterday.", cn: "我们昨天第一次尝试了寿司。" }}, { word: "trying", pos: "v. 现在分词", meaning: "尝试中" , example: { en: "He is trying to fix the old bike.", cn: "他正在试着修理那辆旧自行车。" }}, { word: "try", pos: "n.", meaning: "尝试（have a try）" , example: { en: "Have a try — you can do it!", cn: "试一下吧——你能做到的！" }}],usage: ["try doing sth. 尝试做某事", "try to do sth. 努力去做某事", "try one's best to do sth. 尽某人最大努力去做某事", "have a try 试一下"],
    example: { en: "Let's try windsurfing this weekend.", cn: "这个周末我们试试帆板运动吧。" } },
  { id: 3, word: "take up gardening", pos: "短语", meaning: "从事园艺",
    section: "P14-15 Viewing & Listening",
    usage: ["take up (doing) sth. 开始从事（做）某事；占据"] },
  { id: 4, word: "go rock climbing", pos: "短语", meaning: "去攀岩",
    section: "P14-15 Viewing & Listening",
    usage: ["go doing sth. 去做某事"] },
  { id: 5, word: "act", pos: "v.", meaning: "行动；扮演",
    section: "P14-15 Viewing & Listening",
    derivatives: [{ word: "action", pos: "n.", meaning: "行为；动作" , example: { en: "We must take action now.", cn: "我们现在必须采取行动。" }}, { word: "active", pos: "adj.", meaning: "积极的；活跃的" , example: { en: "She is active in the school club.", cn: "她在社团里很活跃。" }}, { word: "actively", pos: "adv.", meaning: "积极地；主动地" , example: { en: "He actively takes part in class.", cn: "他积极参加课堂活动。" }}, { word: "actor", pos: "n.", meaning: "男演员（复数 actors）" , example: { en: "The actor played a brave hero.", cn: "那位男演员扮演了一位勇敢的英雄。" }}, { word: "actress", pos: "n.", meaning: "女演员（复数 actresses）" , example: { en: "The actress won a big prize.", cn: "那位女演员赢得了一个大奖。" }}, { word: "activity", pos: "n.", meaning: "活动（复数 activities）" , example: { en: "We have many after-school activities.", cn: "我们有很多课外活动。" }}],usage: ["act in a play 参演一部戏剧"] },
  { id: 6, word: "roof", pos: "n.", meaning: "屋顶",
    section: "P14-15 Viewing & Listening",
    usage: ["on the roof 在屋顶上"] },
  { id: 7, word: "use", pos: "v.", meaning: "使用",
    section: "P14-15 Viewing & Listening",
    usage: ["use sth. to do sth. 使用某物去做某事"],
    example: { en: "The children used their hands and feet to climb up the rock wall.", cn: "孩子们手脚并用地爬上攀岩墙。" } },
  { id: 8, word: "change", pos: "v./n.", meaning: "改变；变化",
    section: "P14-15 Viewing & Listening",
    derivatives: [{ word: "changeable", pos: "adj.", meaning: "变幻莫测的" , example: { en: "The weather here is changeable.", cn: "这里的天气变幻莫测。" }}, { word: "changing", pos: "adj.", meaning: "变化中的" , example: { en: "The world is changing fast.", cn: "世界正在快速变化。" }}],example: { en: "The colours of the leaves change with seasons.", cn: "树叶的颜色随着季节变化。" } },
  { id: 9, word: "curious", pos: "adj.", meaning: "好奇的",
    section: "P14-15 Viewing & Listening",
    derivatives: [{ word: "curiosity", pos: "n.", meaning: "好奇心" , example: { en: "Curiosity helps us learn new things.", cn: "好奇心帮助我们学习新事物。" }}, { word: "curiously", pos: "adv.", meaning: "好奇地" , example: { en: "The boy looked at the box curiously.", cn: "男孩好奇地看着那个盒子。" }}],usage: ["be curious about ... 对…感到好奇"],
    example: { en: "I'm very curious about the new technology.", cn: "我对这项新技术非常好奇。" } },
  { id: 10, word: "brave", pos: "adj.", meaning: "勇敢的",
    section: "P14-15 Viewing & Listening",
    derivatives: [{ word: "bravely", pos: "adv.", meaning: "勇敢地" , example: { en: "He bravely told the truth.", cn: "他勇敢地说出了真相。" }}, { word: "bravery", pos: "n.", meaning: "勇气；勇敢" , example: { en: "The fireman was praised for his bravery.", cn: "那位消防员因勇敢而受到表扬。" }}],
    example: { en: "You have to be brave to be a fireman.", cn: "要当消防员一定要很勇敢。" } },
  { id: 11, word: "test", pos: "v./n.", meaning: "测试；检测",
    section: "P14-15 Viewing & Listening",
    usage: ["have / take a test 进行测试"] },
  { id: 12, word: "feeling", pos: "n.", meaning: "感受",
    section: "P14-15 Viewing & Listening",
    derivatives: [{ word: "feel", pos: "v.", meaning: "感受（feel-felt-felt）" , example: { en: "I feel happy today.", cn: "我今天感到开心。" }}, { word: "felt", pos: "v. 过去式", meaning: "感受（过去）" , example: { en: "He felt tired after the game.", cn: "比赛后他感到很疲惫。" }}]},
  { id: 13, word: "traffic", pos: "n.", meaning: "交通（不可数）",
    section: "P14-15 Viewing & Listening",
    usage: ["traffic lights 交通信号灯（可数）", "traffic jam 交通堵塞（可数）"] },
  { id: 14, word: "machine", pos: "n.", meaning: "机器",
    section: "P14-15 Viewing & Listening",
    usage: ["run a machine 运行一台机器", "repair / fix a machine 修理一台机器"] },
  { id: 15, word: "magazine", pos: "n.", meaning: "杂志",
    section: "P14-15 Viewing & Listening",
    synonyms: [{ word: "newspaper", pos: "n.", meaning: "报纸" }, { word: "novel", pos: "n.", meaning: "小说" }] },
  { id: 16, word: "challenge", pos: "n.", meaning: "挑战",
    section: "P14-15 Viewing & Listening",
    derivatives: [{ word: "challenging", pos: "adj.", meaning: "具有挑战性的" , example: { en: "Climbing the mountain is challenging.", cn: "爬山很有挑战性。" }}],usage: ["meet / face a new challenge 面临一个新挑战"] },

  // ===== P16-17 Speaking =====
  { id: 17, word: "craft", pos: "n.", meaning: "手艺；工艺", section: "P16-17 Speaking" },
  { id: 18, word: "improve", pos: "v.", meaning: "提升；改进",
    section: "P16-17 Speaking",
    derivatives: [{ word: "improvement", pos: "n.", meaning: "提升；改进" , example: { en: "We saw a big improvement in his English.", cn: "我们看到他的英语有了很大进步。" }}],usage: ["improve one's life 改善某人的生活"] },
  { id: 19, word: "model", pos: "n.", meaning: "模型",
    section: "P16-17 Speaking",
    usage: ["like building models 喜欢搭建模型"] },
  { id: 20, word: "print", pos: "v.", meaning: "打印",
    section: "P16-17 Speaking",
    derivatives: [{ word: "printer", pos: "n.", meaning: "打印机" , example: { en: "The new printer works well.", cn: "这台新打印机运转良好。" }}, { word: "printing", pos: "n.", meaning: "打印；印刷" , example: { en: "3D printing is amazing.", cn: "3D 打印太神奇了。" }}],
    usage: ["a 3D printing club 3D 打印社团"] },
  { id: 21, word: "gardening", pos: "n.", meaning: "园艺",
    section: "P16-17 Speaking",
    usage: ["improve gardening skills 提升园艺技能"] },
  { id: 22, word: "skate", pos: "v.", meaning: "滑冰",
    section: "P16-17 Speaking",
    usage: ["a skating club 一个滑冰社团"] },
  { id: 23, word: "roof gardening", pos: "n. 短语", meaning: "屋顶园艺",
    section: "P16-17 Speaking",
    usage: ["a roof gardening club 屋顶园艺社团"] },
  { id: 24, word: "sort", pos: "n.", meaning: "种类",
    section: "P16-17 Speaking",
    usage: ["many sorts of = many kinds of 很多种", "all sorts of = all kinds of 所有种类的"] },
  { id: 25, word: "cabbage", pos: "n.", meaning: "卷心菜", section: "P16-17 Speaking" },
  { id: 26, word: "camp", pos: "n./v.", meaning: "营地；露营",
    section: "P16-17 Speaking",
    usage: ["go camping 去露营", "a campsite 一个营地"] },
  { id: 27, word: "grow", pos: "v.", meaning: "生长；种植",
    section: "P16-17 Speaking",
    derivatives: [{ word: "grew", pos: "v. 过去式", meaning: "生长；种植（过去）" , example: { en: "The plant grew quickly in spring.", cn: "春天里这株植物长得很快。" }}, { word: "grown", pos: "v. 过去分词", meaning: "生长；种植（过分）" , example: { en: "He has grown taller this year.", cn: "他今年长高了不少。" }}, { word: "growth", pos: "n.", meaning: "成长；生长" , example: { en: "Growth takes time and care.", cn: "成长需要时间和呵护。" }}],usage: ["grow a plant 种一个植物", "grow up 成长；长大"] },
  { id: 28, word: "join", pos: "v.", meaning: "加入",
    section: "P16-17 Speaking",
    usage: ["join a school club 加入一个学校社团"] },
  { id: 29, word: "care for", pos: "短语 v.", meaning: "照顾",
    section: "P16-17 Speaking",
    usage: ["care for plants 照顾植物", "care for = take care of = look after 照顾（三种表达）"] },
  { id: 30, word: "go hungry", pos: "短语", meaning: "挨饿", section: "P16-17 Speaking" },
  { id: 31, word: "speech club", pos: "n. 短语", meaning: "演讲社团",
    section: "P16-17 Speaking",
    example: { en: "What made you join the speech club?", cn: "什么促使你加入演讲社团？" } },
  { id: 32, word: "What do you mean by ...?", pos: "句型", meaning: "你说的……是什么意思？",
    section: "P16-17 Speaking",
    example: { en: "What do you mean by \"roof gardening\"?", cn: "你说的\"屋顶园艺\"是什么意思？" } },
  { id: 33, word: "would like to", pos: "短语", meaning: "想要（做某事）",
    section: "P16-17 Speaking",
    usage: ["I would like to ... / I want to learn how to grow potatoes 我想学习如何种土豆（两种表达）"] },

  // ===== P18-21 Reading =====
  { id: 34, word: "discuss", pos: "v.", meaning: "讨论",
    section: "P18-21 Reading",
    derivatives: [{ word: "discussion", pos: "n.", meaning: "讨论" , example: { en: "We had a discussion about the project.", cn: "我们讨论了那个项目。" }}],usage: ["discuss sth. with sb. = talk about sth. with sb. 和某人讨论某事（两种）"] },
  { id: 35, word: "everywhere", pos: "adv.", meaning: "到处", section: "P18-21 Reading" },
  { id: 36, word: "impossible", pos: "adj.", meaning: "不可能的",
    section: "P18-21 Reading",
    derivatives: [{ word: "possible", pos: "adj.", meaning: "可能的" , example: { en: "It is possible to finish on time.", cn: "准时完成是可能的。" }}, { word: "possibility", pos: "n.", meaning: "可能性" , example: { en: "There is a possibility of rain.", cn: "有下雨的可能性。" }}, { word: "impossibility", pos: "n.", meaning: "不可能的事（复数 impossibilities）" , example: { en: "Nothing is an impossibility if you keep trying.", cn: "只要坚持尝试，没有事是不可能的。" }}],usage: ["It's impossible to do sth. 做某事是不可能的"] },
  { id: 37, word: "fail", pos: "v.", meaning: "失败",
    section: "P18-21 Reading",
    derivatives: [{ word: "failure", pos: "n.", meaning: "失败" , example: { en: "Failure is the mother of success.", cn: "失败是成功之母。" }}],usage: ["fail (in) sth. 在某事上失败", "fail many times 失败很多次", "fail to do sth. 未能做某事", "be unsuccessful in ... = 在…上失败"] },
  { id: 38, word: "pizza", pos: "n.", meaning: "披萨",
    section: "P18-21 Reading",
    usage: ["a piece of pizza 一片披萨"] },
  { id: 39, word: "burn", pos: "v.", meaning: "燃烧；烫伤",
    section: "P18-21 Reading",
    derivatives: [{ word: "burnt", pos: "v./adj.", meaning: "燃烧（过去）；烧焦的；烧伤的；烫伤的" , example: { en: "He burnt his finger on the stove.", cn: "他的手指被炉子烫到了。" }}, { word: "burned", pos: "v./adj.", meaning: "燃烧（过去，美式）；烧焦的" , example: { en: "The cake burned in the oven.", cn: "蛋糕在烤箱里烤焦了。" }}],usage: ["burn sth. 燃烧某物", "burn oneself 烫伤自己", "get burnt / burned 被烫伤"] },
  { id: 40, word: "separate", pos: "v./adj.", meaning: "分离；分开的",
    section: "P18-21 Reading",
    derivatives: [{ word: "separation", pos: "n.", meaning: "分离；分开" , example: { en: "The separation of the two groups was clear.", cn: "两组的分开很清楚。" }}],usage: ["separate in water 在水中分离", "separate A from B 把 A 从 B 中分离出来", "be separate from 与…分开"] },
  { id: 41, word: "succeed", pos: "v.", meaning: "成功",
    section: "P18-21 Reading",
    derivatives: [{ word: "success", pos: "n.", meaning: "成功" , example: { en: "Hard work brings success.", cn: "努力带来成功。" }}, { word: "successful", pos: "adj.", meaning: "成功的" , example: { en: "He is a successful writer.", cn: "他是一位成功的作家。" }}, { word: "unsuccessful", pos: "adj.", meaning: "不成功的" , example: { en: "The first try was unsuccessful.", cn: "第一次尝试没有成功。" }}, { word: "successfully", pos: "adv.", meaning: "成功地" , example: { en: "They finished the task successfully.", cn: "他们成功地完成了任务。" }}, { word: "unsuccessfully", pos: "adv.", meaning: "不成功地" , example: { en: "He tried unsuccessfully to open the box.", cn: "他没能把盒子打开。" }}],usage: ["succeed in doing sth. 成功做某事", "（反义）fail 失败"],
    example: { en: "After countless tries, we succeeded!", cn: "经过无数次尝试，我们成功了！" } },
  { id: 42, word: "stick", pos: "v./n.", meaning: "粘贴；坚持；棍子",
    section: "P18-21 Reading",
    derivatives: [{ word: "stuck", pos: "v. 过去/分词", meaning: "粘贴；坚持（过去）" , example: { en: "The key was stuck in the lock.", cn: "钥匙卡在锁里了。" }}],usage: ["stick to (doing) sth. 坚持（做）某事", "a stick 一根棍子"] },
  { id: 43, word: "away", pos: "adv.", meaning: "离开",
    section: "P18-21 Reading",
    usage: ["go away 走开", "far away 遥远的"] },
  { id: 44, word: "luckily", pos: "adv.", meaning: "幸运地",
    section: "P18-21 Reading",
    derivatives: [{ word: "lucky", pos: "adj.", meaning: "幸运的" , example: { en: "We are lucky to have good friends.", cn: "我们很幸运有好朋友。" }}, { word: "unlucky", pos: "adj.", meaning: "不幸运的" , example: { en: "The unlucky boy missed the bus.", cn: "那个不幸的男孩没赶上公交车。" }}, { word: "unluckily", pos: "adv.", meaning: "不幸运地" , example: { en: "Unluckily, it started to rain.", cn: "不幸的是，天开始下雨了。" }}, { word: "luck", pos: "n.", meaning: "运气" , example: { en: "Good luck with your test!", cn: "祝你考试好运！" }}]},
  { id: 45, word: "excitedly", pos: "adv.", meaning: "兴奋地；感到兴奋地",
    section: "P18-21 Reading",
    derivatives: [{ word: "excited", pos: "adj.", meaning: "感到兴奋的" , example: { en: "The children were excited about the trip.", cn: "孩子们对这次旅行感到兴奋。" }}, { word: "exciting", pos: "adj.", meaning: "令人兴奋的" , example: { en: "The game was really exciting.", cn: "那场比赛真的很令人兴奋。" }}, { word: "excitement", pos: "n.", meaning: "兴奋；激动" , example: { en: "The kids jumped with excitement.", cn: "孩子们兴奋得跳了起来。" }}],usage: ["shout excitedly 兴奋地大叫"] },
  { id: 46, word: "hopefully", pos: "adv.", meaning: "有希望地",
    section: "P18-21 Reading",
    derivatives: [{ word: "hope", pos: "v./n.", meaning: "希望" , example: { en: "I hope to see you soon.", cn: "我希望很快能见到你。" }}, { word: "hopeful", pos: "adj.", meaning: "充满希望的" , example: { en: "I feel hopeful about the future.", cn: "我对未来充满希望。" }}, { word: "hopeless", pos: "adj.", meaning: "没有希望的；不擅长的" , example: { en: "I am hopeless at singing.", cn: "我完全不擅长唱歌。" }}]},
  { id: 47, word: "countless", pos: "adj.", meaning: "无数的",
    section: "P18-21 Reading",
    synonyms: [{ word: "innumerable", pos: "adj.", meaning: "无数的（近义）" }],
    usage: ["after countless tries 经过无数次尝试"] },
  { id: 48, word: "energy", pos: "n.", meaning: "能量；精力",
    section: "P18-21 Reading",
    derivatives: [{ word: "energetic", pos: "adj.", meaning: "精力充沛的" , example: { en: "My dog is very energetic.", cn: "我的狗精力充沛。" }}],usage: ["have energy 有精力", "renewable energy 可再生能源", "solar energy 太阳能"] },
  { id: 49, word: "try something new", pos: "短语", meaning: "尝试新事物",
    section: "P18-21 Reading",
    usage: ["try new things 尝试新事物"] },
  { id: 50, word: "power", pos: "v.", meaning: "为……供电；驱动",
    section: "P18-21 Reading",
    derivatives: [{ word: "powerful", pos: "adj.", meaning: "有力的；强大的" , example: { en: "The storm was powerful.", cn: "那场暴风雨很猛烈。" }}, { word: "powerless", pos: "adj.", meaning: "无能为力的" , example: { en: "He felt powerless to change it.", cn: "他觉得无力改变这件事。" }}],example: { en: "With these solar stickers, we can power the world.", cn: "有了这些太阳能贴纸，我们就可以为全世界供电。" } },
  { id: 51, word: "solar", pos: "adj.", meaning: "太阳能的",
    section: "P18-21 Reading",
    usage: ["solar energy 太阳能", "solar panel 太阳能电池板", "solar cell 太阳能电池"] },
  { id: 52, word: "test this new idea", pos: "短语", meaning: "测试这个新想法",
    section: "P18-21 Reading" },
  { id: 53, word: "hurry to the lab", pos: "短语", meaning: "急忙赶到实验室",
    section: "P18-21 Reading",
    usage: ["hurry v. 急忙"] },
  { id: 54, word: "renewable energy", pos: "n. 短语", meaning: "可再生能源",
    section: "P18-21 Reading",
    example: { en: "Sunlight makes us warm and brings us renewable energy.", cn: "阳光让我们感到温暖，并为我们带来可再生能源。" } },
  { id: 55, word: "collect and use solar energy", pos: "短语", meaning: "收集并使用太阳能",
    section: "P18-21 Reading",
    example: { en: "We often discuss how wonderful it will be to collect and use solar energy everywhere.", cn: "我们经常讨论如果能在任何地方都收集和使用太阳能，那将多么美好。" } },
  { id: 56, word: "using solar energy", pos: "短语", meaning: "利用太阳能",
    section: "P18-21 Reading",
    example: { en: "In the past, people thought using solar energy was impossible.", cn: "过去，人们认为利用太阳能是不可能的。" } },
  { id: 57, word: "fail many times", pos: "短语", meaning: "多次失败",
    section: "P18-21 Reading",
    example: { en: "We tried many times to make it light, but we failed.", cn: "我们多次尝试让它亮起来，但都没有成功。" } },
  { id: 58, word: "get burned", pos: "短语", meaning: "被烫伤",
    section: "P18-21 Reading",
    example: { en: "One of us got burned while moving the pan.", cn: "我们中的一个人在移动烤盘时被烫伤了。" } },
  { id: 59, word: "hurry to the lab", pos: "短语", meaning: "急忙赶到实验室",
    section: "P18-21 Reading",
    example: { en: "We hurried to the lab to test the new idea.", cn: "我们急忙赶到实验室测试这个新想法。" } },
  { id: 60, word: "succeed", pos: "v.", meaning: "成功",
    section: "P18-21 Reading",
    example: { en: "After countless tries, we succeeded!", cn: "经过无数次尝试，我们成功了！" } },
  { id: 61, word: "power the world", pos: "短语", meaning: "为全世界供电",
    section: "P18-21 Reading",
    example: { en: "With these solar stickers, we can power the world.", cn: "有了这些太阳能贴纸，我们就可以为全世界供电。" } },

  // ===== P22-23 Grammar =====
  { id: 62, word: "call sb. ...", pos: "短语", meaning: "把……称为……",
    section: "P22-23 Grammar",
    usage: ["call them vegetable animals 称他们为蔬菜动物"] },
  { id: 63, word: "grow up in a town", pos: "短语", meaning: "在一个小镇长大",
    section: "P22-23 Grammar" },
  { id: 64, word: "take cold baths", pos: "短语", meaning: "泡冷水澡",
    section: "P22-23 Grammar",
    usage: ["take a cold bath 泡冷水澡"] },
  { id: 65, word: "a water bottle", pos: "短语", meaning: "水瓶", section: "P22-23 Grammar" },
  { id: 66, word: "a rubber tube", pos: "短语", meaning: "橡皮管", section: "P22-23 Grammar" },
  { id: 67, word: "a water heater", pos: "短语", meaning: "热水器", section: "P22-23 Grammar" },
  { id: 68, word: "finish doing sth.", pos: "短语", meaning: "完成做某事",
    section: "P22-23 Grammar",
    example: { en: "She finished washing the clothes.", cn: "她洗完衣服了。" } },
  { id: 69, word: "washing machine", pos: "n. 短语", meaning: "洗衣机",
    section: "P22-23 Grammar",
    usage: ["put the clothes into a washing machine 把衣服放进洗衣机"] },
  { id: 70, word: "invent", pos: "v.", meaning: "发明",
    section: "P22-23 Grammar",
    derivatives: [{ word: "invention", pos: "n.", meaning: "发明物" , example: { en: "The telephone was a great invention.", cn: "电话是一项伟大的发明。" }}, { word: "inventor", pos: "n.", meaning: "发明者" , example: { en: "Edison was a famous inventor.", cn: "爱迪生是著名的发明家。" }}],example: { en: "People think my invention is very useful.", cn: "人们认为我的发明非常有用。" } },
  { id: 71, word: "make", pos: "v.", meaning: "制作；做；使得",
    section: "P22-23 Grammar",
    derivatives: [{ word: "made", pos: "v. 过去/分词", meaning: "制作；使得（过去）" , example: { en: "She made a card for her mum.", cn: "她给妈妈做了一张卡片。" }}],example: { en: "They made me a prize winner.", cn: "他们选我为获奖者。" } },
  { id: 72, word: "ill", pos: "adj.", meaning: "生病的；感到恶心的",
    section: "P22-23 Grammar",
    example: { en: "She was ill from eating too much junk food.", cn: "她因为吃太多垃圾食品而生病了。" } },

  // ===== P24-25 Writing =====
  { id: 73, word: "solve", pos: "v.", meaning: "解决",
    section: "P24-25 Writing",
    synonyms: [{ word: "work out", pos: "短语", meaning: "解决（同义）" }],
    derivatives: [{ word: "solution", pos: "n.", meaning: "解决办法；答案" , example: { en: "We found a solution to the problem.", cn: "我们找到了这个问题的解决办法。" }}],usage: ["solve a problem 解决一个问题", "a solution to sth. 某事的解决办法"] },
  { id: 74, word: "stick to doing sth.", pos: "短语", meaning: "坚持做某事",
    section: "P24-25 Writing",
    usage: ["a stick 一根棍子", "stick-stuck-stuck 粘贴；坚持（过去）"] },
  { id: 75, word: "umbrella", pos: "n.", meaning: "雨伞",
    section: "P24-25 Writing",
    usage: ["an umbrella 一把雨伞"] },
  { id: 76, word: "handle", pos: "n./v.", meaning: "把手；处理",
    section: "P24-25 Writing",
    usage: ["the handle of sth. 某物的把手", "handle a problem 处理一个问题"] },
  { id: 77, word: "proud", pos: "adj.", meaning: "骄傲的；自豪的",
    section: "P24-25 Writing",
    derivatives: [{ word: "pride", pos: "n.", meaning: "骄傲；自豪" , example: { en: "He felt pride in his work.", cn: "他对自己的工作感到自豪。" }}],usage: ["be proud of 为…感到骄傲"] },
  { id: 78, word: "creative", pos: "adj.", meaning: "有创造力的",
    section: "P24-25 Writing",
    derivatives: [{ word: "create", pos: "v.", meaning: "创造" , example: { en: "We can create art with our hands.", cn: "我们可以用双手创造艺术。" }}, { word: "creativity", pos: "n.", meaning: "创造力" , example: { en: "Reading helps build creativity.", cn: "阅读有助于培养创造力。" }}],usage: ["a creative idea 一个有创意的想法"] },
  { id: 79, word: "grader", pos: "n.", meaning: "……年级学生",
    section: "P24-25 Writing",
    usage: ["a six grader 一个六年级学生"] },
  { id: 80, word: "experience", pos: "n./v.", meaning: "经验（不可数）；经历（可数）；经历（动词）",
    section: "P24-25 Writing",
    usage: ["have much experience 有很多经验（不可数）", "an interesting experience 一次有趣的经历（可数）", "experience sth. 经历某事"] },
  { id: 81, word: "difficulty", pos: "n.", meaning: "困难",
    section: "P24-25 Writing",
    derivatives: [{ word: "difficult", pos: "adj.", meaning: "困难的" , example: { en: "English is not difficult if you practise.", cn: "只要多加练习，英语并不难。" }}],usage: ["have difficulty (in) doing sth. 做某事有困难"] },

  // ===== P26-27 Discovery & Project =====
  { id: 82, word: "ancient", pos: "adj.", meaning: "古老的",
    section: "P26-27 Discovery & Project",
    antonyms: [{ word: "modern", pos: "adj.", meaning: "现代的（反义）" }],
    usage: ["an ancient city 一座古老的城市"] },
  { id: 83, word: "store", pos: "n./v.", meaning: "百货商店；储存",
    section: "P26-27 Discovery & Project",
    derivatives: [{ word: "storage", pos: "n.", meaning: "储存" , example: { en: "We need more storage for our photos.", cn: "我们需要更多空间来储存照片。" }}],usage: ["a department store 一家百货商店", "store sth. 储存某物", "store ice 储存冰块"] },
  { id: 84, word: "break the ice into pieces", pos: "短语", meaning: "把冰块打碎",
    section: "P26-27 Discovery & Project" },
  { id: 85, word: "make ... safer", pos: "短语", meaning: "使……更安全",
    section: "P26-27 Discovery & Project",
    usage: ["safe adj. 安全的"] },
  { id: 86, word: "cut her fingers", pos: "短语", meaning: "割伤她的手指",
    section: "P26-27 Discovery & Project",
    usage: ["burn her fingers 烫伤她的手指"] },
  { id: 87, word: "mix", pos: "v.", meaning: "混合",
    section: "P26-27 Discovery & Project",
    derivatives: [{ word: "mixture", pos: "n.", meaning: "混合物" , example: { en: "The cake is a mixture of flour and eggs.", cn: "蛋糕是面粉和鸡蛋的混合物。" }}, { word: "mixed", pos: "adj.", meaning: "混合的" , example: { en: "She felt mixed feelings.", cn: "她百感交集。" }}],usage: ["mix A with B 把 A 和 B 混合"] },
  { id: 88, word: "course", pos: "n.", meaning: "课程",
    section: "P26-27 Discovery & Project",
    usage: ["of course 当然", "a course of study 一门课程的学习"] },
  { id: 89, word: "flavour", pos: "n.", meaning: "味道",
    section: "P26-27 Discovery & Project",
    derivatives: [{ word: "flavourful", pos: "adj.", meaning: "美味的；有香味的" , example: { en: "The soup is flavourful and warm.", cn: "这汤美味又暖胃。" }}],usage: ["a strong flavour 强烈的味道"] },
  { id: 90, word: "sticky", pos: "adj.", meaning: "黏糊糊的",
    section: "P26-27 Discovery & Project",
    derivatives: [{ word: "sticker", pos: "n.", meaning: "贴纸" , example: { en: "These solar stickers can power a lamp.", cn: "这些太阳能贴纸能给台灯供电。" }}],
    usage: ["sticky fingers 黏糊糊的手指"] },
  { id: 91, word: "cloth", pos: "n.", meaning: "布料",
    section: "P26-27 Discovery & Project",
    usage: ["a piece of cloth 一块布", "clothes 衣服（复数）", "clothing 衣服（总称，不可数）"] },
  { id: 92, word: "square", pos: "n./adj.", meaning: "正方形；正方形的",
    section: "P26-27 Discovery & Project",
    usage: ["a public square 一个公共广场", "a square table 一张方形的桌子"] },
  { id: 93, word: "cotton", pos: "n.", meaning: "棉花",
    section: "P26-27 Discovery & Project",
    usage: ["cotton clothes 棉质的衣服"] },
  { id: 94, word: "come into being", pos: "短语", meaning: "形成；产生",
    section: "P26-27 Discovery & Project",
    example: { en: "The custom came into being long ago.", cn: "这个习俗很久以前就形成了。" } },
  { id: 95, word: "basic", pos: "adj.", meaning: "基础的",
    section: "P26-27 Discovery & Project",
    derivatives: [{ word: "base", pos: "n.", meaning: "基础；底部" , example: { en: "We should learn the base first.", cn: "我们应该先学基础。" }}],usage: ["basic knowledge 基础知识"] },
  { id: 96, word: "enroll in", pos: "短语", meaning: "报名；参加",
    section: "P26-27 Discovery & Project",
    usage: ["enroll in an online course 报名参加一门在线课程"] },
  { id: 97, word: "goal", pos: "n.", meaning: "目标",
    section: "P26-27 Discovery & Project",
    usage: ["set a goal 设立一个目标", "achieve one's goal 实现某人的目标"] },
  { id: 98, word: "remind", pos: "v.", meaning: "提醒；使想起",
    section: "P26-27 Discovery & Project",
    derivatives: [{ word: "reminder", pos: "n.", meaning: "提醒物；提示" , example: { en: "The note is a reminder for me.", cn: "这张便条是我的提醒。" }}],usage: ["remind sb. of sth. 使某人想起某事", "remind sb. (not) to do sth. 提醒某人（不）去做某事"] },
  { id: 99, word: "progress", pos: "n./v.", meaning: "进步（不可数）",
    section: "P26-27 Discovery & Project",
    usage: ["make much progress 取得很大进步", "check my progress 检查我的进步", "progress smoothly 进展顺利"] },

  // ===== 学习小贴士（P28） =====
  { id: 100, word: "make a time plan", pos: "短语", meaning: "制定一个时间计划", section: "学习小贴士" },
  { id: 101, word: "keep on practising", pos: "短语", meaning: "不断练习", section: "学习小贴士" },
  { id: 102, word: "set alarm clocks", pos: "短语", meaning: "设闹钟", section: "学习小贴士" },
  { id: 103, word: "join a dancing club", pos: "短语", meaning: "加入舞蹈社团", section: "学习小贴士" },
  { id: 104, word: "every two weeks", pos: "短语", meaning: "每两周／每隔一周", section: "学习小贴士" },

  // ===== U1 课堂笔记补充（优秀笔记整理，2026-09） =====
  { id: 105, word: "material", pos: "n.", meaning: "材料；原料",
    section: "U1 课堂笔记补充",
    derivatives: [{ word: "materially", pos: "adv.", meaning: "物质上；实质上" }],
    usage: ["raw materials 原材料", "building materials 建筑材料"],
    example: { en: "We need good materials to make the model.", cn: "我们需要好的材料来制作模型。" } },
  { id: 106, word: "metal", pos: "n.", meaning: "金属",
    section: "U1 课堂笔记补充",
    example: { en: "The box is made of metal.", cn: "这个盒子是金属做的。" } },
  { id: 107, word: "layer", pos: "n.", meaning: "层；层次",
    section: "U1 课堂笔记补充",
    usage: ["a layer of ... 一层……"],
    example: { en: "There is a thick layer of snow on the road.", cn: "路上有一层厚厚的雪。" } },
  { id: 108, word: "cell", pos: "n.", meaning: "电池；细胞",
    section: "U1 课堂笔记补充",
    usage: ["solar cell 太阳能电池"],
    example: { en: "A solar cell can change sunlight into electricity.", cn: "太阳能电池能把阳光变成电。" } },
  { id: 109, word: "holder", pos: "n.", meaning: "支架；持有者",
    section: "U1 课堂笔记补充",
    usage: ["a phone holder 手机支架", "a record holder 纪录保持者"],
    example: { en: "He fixed the phone in a holder.", cn: "他把手机固定在支架上。" } },
  { id: 110, word: "technology", pos: "n.", meaning: "科技；技术",
    section: "U1 课堂笔记补充",
    derivatives: [{ word: "technological", pos: "adj.", meaning: "科技的" , example: { en: "Technological changes are fast.", cn: "科技变化很快。" }}],
    usage: ["science and technology 科学技术"],
    example: { en: "New technology makes our life easier.", cn: "新技术让生活更方便。" } },
  { id: 111, word: "troublesome", pos: "adj.", meaning: "麻烦的；令人烦恼的",
    section: "U1 课堂笔记补充",
    usage: ["troublesome problems 麻烦的问题"],
    example: { en: "The noisy machine is troublesome.", cn: "这台吵闹的机器很麻烦。" } },
  { id: 112, word: "determined", pos: "adj.", meaning: "坚定的；下决心的",
    section: "U1 课堂笔记补充",
    derivatives: [{ word: "determination", pos: "n.", meaning: "决心" , example: { en: "She shows great determination.", cn: "她表现出极大的决心。" }}],
    usage: ["be determined to do sth. 下决心做某事"],
    example: { en: "He is determined to learn swimming.", cn: "他下定决心要学游泳。" } },
  { id: 113, word: "realize", pos: "v.", meaning: "意识到；实现",
    section: "U1 课堂笔记补充",
    derivatives: [{ word: "real", pos: "adj.", meaning: "真实的" , example: { en: "This is a real story.", cn: "这是一个真实的故事。" }}, { word: "really", pos: "adv.", meaning: "真正地" , example: { en: "I really like it.", cn: "我真的很喜欢它。" }}],
    usage: ["realize one's dream 实现梦想"],
    example: { en: "I didn't realize the importance of practice.", cn: "我没有意识到练习的重要性。" } },
  { id: 114, word: "overcome", pos: "v.", meaning: "克服；战胜（overcame, overcome）",
    section: "U1 课堂笔记补充",
    usage: ["overcome difficulties 克服困难", "overcome fear 克服恐惧"],
    example: { en: "She overcame her shyness and spoke first.", cn: "她克服了害羞，第一个发言。" } },
  { id: 115, word: "accept", pos: "v.", meaning: "接受",
    section: "U1 课堂笔记补充",
    derivatives: [{ word: "acceptable", pos: "adj.", meaning: "可接受的" , example: { en: "The answer is acceptable.", cn: "这个答案是可以接受的。" }}],
    usage: ["accept the invitation 接受邀请", "accept that ... 接受……"],
    example: { en: "Please accept my gift.", cn: "请接受我的礼物。" } },
  { id: 116, word: "acceptable", pos: "adj.", meaning: "可接受的",
    section: "U1 课堂笔记补充",
    example: { en: "His behaviour is not acceptable.", cn: "他的行为是不可接受的。" } },
  { id: 117, word: "refuse", pos: "v.", meaning: "拒绝",
    section: "U1 课堂笔记补充",
    derivatives: [{ word: "refusal", pos: "n.", meaning: "拒绝" , example: { en: "Her refusal surprised us.", cn: "她的拒绝让我们吃惊。" }}],
    usage: ["refuse to do sth. 拒绝做某事"],
    example: { en: "He refused to give up.", cn: "他拒绝放弃。" } },
  { id: 118, word: "reject", pos: "v.", meaning: "拒绝；摒弃",
    section: "U1 课堂笔记补充",
    usage: ["reject an idea 否定一个想法"],
    example: { en: "The team rejected my idea at first.", cn: "团队起初否定了我的想法。" } },
  { id: 119, word: "praise", pos: "v./n.", meaning: "表扬；赞扬",
    section: "U1 课堂笔记补充",
    usage: ["praise sb. for sth. 因某事表扬某人"],
    example: { en: "The teacher praised him for his bravery.", cn: "老师表扬了他的勇敢。" } },
  { id: 120, word: "ignore", pos: "v.", meaning: "忽视；不理",
    section: "U1 课堂笔记补充",
    usage: ["ignore the mistakes 忽视错误"],
    example: { en: "Don't ignore small problems.", cn: "不要忽视小问题。" } },
  { id: 121, word: "space", pos: "n.", meaning: "空间；太空",
    section: "U1 课堂笔记补充",
    usage: ["in space 在太空中", "make space for ... 为……腾出空间"],
    example: { en: "The desk takes up too much space.", cn: "这张桌子占了太多空间。" } },
  { id: 122, word: "rapid", pos: "adj.", meaning: "快速的",
    section: "U1 课堂笔记补充",
    derivatives: [{ word: "rapidly", pos: "adv.", meaning: "快速地" , example: { en: "The city is developing rapidly.", cn: "这座城市正在快速发展。" }}],
    usage: ["rapid progress 快速的进步", "rapidly growing 快速增长的"],
    example: { en: "He made rapid progress in English.", cn: "他英语进步很快。" } },
  { id: 123, word: "simple", pos: "adj.", meaning: "简单的",
    section: "U1 课堂笔记补充",
    derivatives: [{ word: "simply", pos: "adv.", meaning: "简单地；仅仅" , example: { en: "It is simply a test.", cn: "这只是一次测试。" }}],
    usage: ["simple questions 简单的问题"],
    example: { en: "The answer is quite simple.", cn: "答案很简单。" } },
  { id: 124, word: "hungry", pos: "adj.", meaning: "饥饿的",
    section: "U1 课堂笔记补充",
    derivatives: [{ word: "hunger", pos: "n.", meaning: "饥饿" , example: { en: "Hunger is a big problem in some areas.", cn: "饥饿在一些地区是个大问题。" }}],
    usage: ["be hungry for ... 渴望……", "go hungry 挨饿"],
    example: { en: "After the game, I felt really hungry.", cn: "比赛之后，我真的很饿。" } },
  { id: 125, word: "collect", pos: "v.", meaning: "收集；聚集",
    section: "U1 课堂笔记补充",
    derivatives: [{ word: "collection", pos: "n.", meaning: "收藏品；收集" , example: { en: "He has a stamp collection.", cn: "他有一套邮票收藏。" }}],
    usage: ["collect stamps 收集邮票", "collect information 收集信息"],
    example: { en: "We collect old books for the school library.", cn: "我们为学校图书馆收集旧书。" } },
  { id: 126, word: "member", pos: "n.", meaning: "成员",
    section: "U1 课堂笔记补充",
    usage: ["a club member 社团成员", "family members 家庭成员"],
    example: { en: "There are twenty members in our team.", cn: "我们队有二十名成员。" } },
  { id: 127, word: "think", pos: "v.", meaning: "思考；认为（thought, thought）",
    section: "U1 课堂笔记补充",
    derivatives: [{ word: "thought", pos: "n./v.", meaning: "想法；思考（think 的过去式）" , example: { en: "I thought about it carefully.", cn: "我仔细想了想。" }}],
    usage: ["think about ... 思考……", "think of ... 想起；认为", "think over 仔细考虑"],
    example: { en: "Think it over before you start.", cn: "开始之前仔细考虑一下。" } },
  { id: 128, word: "coin", pos: "n.", meaning: "硬币",
    section: "U1 课堂笔记补充",
    usage: ["Every coin has its two sides. 事物都有两面性"],
    example: { en: "Every coin has its two sides, and so does the phone.", cn: "事物都有两面性，手机也一样。" } },
  { id: 129, word: "courage", pos: "n.", meaning: "勇气",
    section: "U1 课堂笔记补充",
    derivatives: [{ word: "encourage", pos: "v.", meaning: "鼓励" , example: { en: "The teacher encouraged us to try again.", cn: "老师鼓励我们再试一次。" }}, { word: "encouragement", pos: "n.", meaning: "鼓励" , example: { en: "Thanks for your encouragement.", cn: "谢谢你的鼓励。" }}],
    usage: ["have the courage to do sth. 有勇气做某事"],
    example: { en: "It takes courage to try new things.", cn: "尝试新事物需要勇气。" } },
  { id: 130, word: "confidence", pos: "n.", meaning: "自信；信心",
    section: "U1 课堂笔记补充",
    derivatives: [{ word: "confident", pos: "adj.", meaning: "自信的" , example: { en: "Be confident in yourself.", cn: "对自己要有信心。" }}],
    usage: ["build up confidence 建立自信", "have confidence in ... 对……有信心"],
    example: { en: "Practice gives us confidence.", cn: "练习给我们自信。" } },
  { id: 131, word: "trust", pos: "v./n.", meaning: "信任",
    section: "U1 课堂笔记补充",
    usage: ["trust each other 相互信任"],
    example: { en: "Trust yourself and keep going.", cn: "相信自己，继续前进。" } },
  { id: 132, word: "instead", pos: "adv.", meaning: "代替；反而",
    section: "U1 课堂笔记补充",
    usage: ["instead of (doing) sth. 而不是（做）某事"],
    example: { en: "He didn't watch TV; instead, he read a book.", cn: "他没看电视，而是读了本书。" } },
  { id: 133, word: "however", pos: "adv./conj.", meaning: "然而；不过",
    section: "U1 课堂笔记补充",
    example: { en: "The plan is good. However, it costs too much.", cn: "这个计划不错。然而，花费太高。" } },
  { id: 134, word: "advantage", pos: "n.", meaning: "优点；优势",
    section: "U1 课堂笔记补充",
    derivatives: [{ word: "disadvantage", pos: "n.", meaning: "缺点；不利" , example: { en: "Every plan has its advantages and disadvantages.", cn: "每个计划都有优缺点。" }}],
    usage: ["take advantage of ... 利用……"],
    example: { en: "The new phone has many advantages.", cn: "这款新手机有很多优点。" } }
];

// 单元信息
const UNIT_INFO = {
  title: "7A Unit 1  Trying new things",
  subtitle: "尝试新事物 · 词汇练习",
  total: VOCAB.length
};
