// 词形变换词库（覆盖卷3错词 + 中考常见家族）
// 字段：from 原词 / fromPos 原词性 / toPos 目标词性 / answer 答案 / meaning 答案含义 / example 例句 / unit 归属单元
// unit：U1-U7 挂到对应单元；MIDDLE 为「中考词性转换」独立分区
window.FORMS_BANK = [
  { from: 'success', fromPos: 'n.', toPos: 'adj.', answer: 'successful', meaning: '成功的', example: { en: 'He is a successful writer.', cn: '他是一位成功的作家。' }, unit: 'U1' },
  { from: 'success', fromPos: 'n.', toPos: 'v.', answer: 'succeed', meaning: '成功', example: { en: 'He succeeded at last.', cn: '他最终成功了。' }, unit: 'U1' },
  { from: 'successful', fromPos: 'adj.', toPos: 'adv.', answer: 'successfully', meaning: '成功地', example: { en: 'They finished successfully.', cn: '他们成功完成了。' }, unit: 'U1' },
  { from: 'succeed', fromPos: 'v.', toPos: 'n.', answer: 'success', meaning: '成功', example: { en: 'Failure is the mother of success.', cn: '失败是成功之母。' }, unit: 'U1' },
  { from: 'excite', fromPos: 'v.', toPos: 'adj.', answer: 'exciting', meaning: '令人兴奋的', example: { en: 'It was an exciting game.', cn: '那是一场令人兴奋的比赛。' }, unit: 'U4' },
  { from: 'excite', fromPos: 'v.', toPos: 'n.', answer: 'excitement', meaning: '兴奋', example: { en: 'The children jumped with excitement.', cn: '孩子们兴奋地跳起来。' }, unit: 'U4' },
  { from: 'luck', fromPos: 'n.', toPos: 'adj.', answer: 'lucky', meaning: '幸运的', example: { en: 'He is a lucky boy.', cn: '他是个幸运的男孩。' }, unit: 'U1' },
  { from: 'lucky', fromPos: 'adj.', toPos: 'adv.', answer: 'luckily', meaning: '幸运地', example: { en: 'Luckily, nobody was hurt.', cn: '幸运的是，没人受伤。' }, unit: 'U1' },
  { from: 'discuss', fromPos: 'v.', toPos: 'n.', answer: 'discussion', meaning: '讨论', example: { en: 'We had a discussion about it.', cn: '我们讨论了这件事。' }, unit: 'U1' },
  { from: 'print', fromPos: 'v.', toPos: 'v.-ed/-pp', answer: 'printed', meaning: '打印（过去式/分词）', example: { en: 'She printed a picture.', cn: '她打印了一幅画。' }, unit: 'U1' },
  { from: 'challenge', fromPos: 'n.', toPos: 'adj.', answer: 'challenging', meaning: '有挑战性的', example: { en: 'This job is challenging.', cn: '这份工作很有挑战性。' }, unit: 'U1' },
  { from: 'confidence', fromPos: 'n.', toPos: 'adj.', answer: 'confident', meaning: '自信的', example: { en: 'He is confident about it.', cn: '他对此很自信。' }, unit: 'MIDDLE' },
  { from: 'brave', fromPos: 'adj.', toPos: 'adv.', answer: 'bravely', meaning: '勇敢地', example: { en: 'He faced it bravely.', cn: '他勇敢地面对它。' }, unit: 'U1' },
  { from: 'brave', fromPos: 'adj.', toPos: 'n.', answer: 'bravery', meaning: '勇气；勇敢', example: { en: 'The fireman was praised for his bravery.', cn: '那位消防员因勇敢而受到表扬。' }, unit: 'U1' },
  { from: 'curious', fromPos: 'adj.', toPos: 'n.', answer: 'curiosity', meaning: '好奇心', example: { en: 'Curiosity drives us to explore.', cn: '好奇心驱使我们去探索。' }, unit: 'U1' },
  { from: 'possible', fromPos: 'adj.', toPos: 'n.', answer: 'possibility', meaning: '可能性', example: { en: 'There is a possibility of rain.', cn: '有下雨的可能性。' }, unit: 'U1' },
  { from: 'impossible', fromPos: 'adj.', toPos: 'n.', answer: 'impossibility', meaning: '不可能的事', example: { en: 'Nothing is an impossibility.', cn: '没有什么是不可能的。' }, unit: 'U1' },
  { from: 'hope', fromPos: 'v./n.', toPos: 'adj.', answer: 'hopeful', meaning: '充满希望的', example: { en: 'I feel hopeful about the future.', cn: '我对未来充满希望。' }, unit: 'U1' },
  { from: 'hope', fromPos: 'v./n.', toPos: 'adj.(否定)', answer: 'hopeless', meaning: '没有希望的', example: { en: 'I am hopeless at singing.', cn: '我完全不擅长唱歌。' }, unit: 'U1' },
  { from: 'stick', fromPos: 'v.', toPos: 'n.', answer: 'sticker', meaning: '贴纸', example: { en: 'These solar stickers can power a lamp.', cn: '这些太阳能贴纸能给台灯供电。' }, unit: 'U1' },
  { from: 'stick', fromPos: 'v.', toPos: 'adj.', answer: 'sticky', meaning: '黏糊糊的', example: { en: 'My hands are sticky.', cn: '我的手黏糊糊的。' }, unit: 'U1' },
  { from: 'realize', fromPos: 'v.', toPos: 'adj.', answer: 'real', meaning: '真实的', example: { en: 'This is a real story.', cn: '这是一个真实的故事。' }, unit: 'U1' },
  { from: 'rapid', fromPos: 'adj.', toPos: 'adv.', answer: 'rapidly', meaning: '快速地', example: { en: 'The city is developing rapidly.', cn: '这座城市正在快速发展。' }, unit: 'U1' },
  { from: 'collect', fromPos: 'v.', toPos: 'n.', answer: 'collection', meaning: '收藏品；收集', example: { en: 'He has a stamp collection.', cn: '他有一套邮票收藏。' }, unit: 'U1' },
  { from: 'think', fromPos: 'v.', toPos: 'n.', answer: 'thought', meaning: '想法；思考', example: { en: 'Please share your thoughts with us.', cn: '请和我们分享你的想法。' }, unit: 'U1' },
  { from: 'courage', fromPos: 'n.', toPos: 'v.', answer: 'encourage', meaning: '鼓励', example: { en: 'The teacher encouraged us to try again.', cn: '老师鼓励我们再试一次。' }, unit: 'U1' },
  { from: 'courage', fromPos: 'n.', toPos: 'n.(名词化)', answer: 'encouragement', meaning: '鼓励', example: { en: 'Thanks for your encouragement.', cn: '谢谢你的鼓励。' }, unit: 'U1' },
  { from: 'determine', fromPos: 'v.', toPos: 'adj.', answer: 'determined', meaning: '坚定的；下决心的', example: { en: 'He is determined to learn swimming.', cn: '他下定决心要学游泳。' }, unit: 'U1' },
  { from: 'accept', fromPos: 'v.', toPos: 'adj.', answer: 'acceptable', meaning: '可接受的', example: { en: 'The answer is acceptable.', cn: '这个答案是可以接受的。' }, unit: 'U1' },
  { from: 'refuse', fromPos: 'v.', toPos: 'n.', answer: 'refusal', meaning: '拒绝', example: { en: 'Her refusal surprised us.', cn: '她的拒绝让我们吃惊。' }, unit: 'U1' },
  { from: 'hunger', fromPos: 'n.', toPos: 'adj.', answer: 'hungry', meaning: '饥饿的', example: { en: 'After the game, I felt really hungry.', cn: '比赛之后，我真的很饿。' }, unit: 'U1' },
  { from: 'member', fromPos: 'n.', toPos: 'n.-pl', answer: 'members', meaning: '成员（复数）', example: { en: 'There are twenty members in our team.', cn: '我们队有二十名成员。' }, unit: 'U1' },
  { from: 'care', fromPos: 'n.', toPos: 'adj.', answer: 'careful', meaning: '小心的', example: { en: 'Be careful with the glass.', cn: '小心那个玻璃杯。' }, unit: 'U5' },
  { from: 'careful', fromPos: 'adj.', toPos: 'adv.', answer: 'carefully', meaning: '小心地', example: { en: 'Listen carefully, please.', cn: '请仔细听。' }, unit: 'U5' },
  { from: 'help', fromPos: 'v.', toPos: 'adj.', answer: 'helpful', meaning: '有帮助的', example: { en: 'The tip was helpful.', cn: '这个提示很有帮助。' }, unit: 'MIDDLE' },
  { from: 'power', fromPos: 'n.', toPos: 'adj.', answer: 'powerful', meaning: '强大的', example: { en: 'China is a powerful country.', cn: '中国是一个强大的国家。' }, unit: 'U1' },
  { from: 'count', fromPos: 'v.', toPos: 'adj.', answer: 'countless', meaning: '无数的', example: { en: 'There are countless stars.', cn: '有无数的星星。' }, unit: 'MIDDLE' },
  { from: 'simple', fromPos: 'adj.', toPos: 'adv.', answer: 'simply', meaning: '简单地；仅仅', example: { en: 'It is simply wrong.', cn: '这简直是错的。' }, unit: 'U4' },
  { from: 'importance', fromPos: 'n.', toPos: 'adj.', answer: 'important', meaning: '重要的', example: { en: 'This is an important test.', cn: '这是一次重要的考试。' }, unit: 'U7' },
  { from: 'important', fromPos: 'adj.', toPos: 'n.', answer: 'importance', meaning: '重要性', example: { en: 'He knows the importance of health.', cn: '他知道健康的重要性。' }, unit: 'U7' },
  { from: 'respect', fromPos: 'v.', toPos: 'adj.', answer: 'respectful', meaning: '尊敬的', example: { en: 'Be respectful to teachers.', cn: '要尊敬老师。' }, unit: 'U4' },
  { from: 'distance', fromPos: 'n.', toPos: 'adj.', answer: 'distant', meaning: '遥远的', example: { en: 'A distant country.', cn: '一个遥远的国家。' }, unit: 'U4' },
  { from: 'trust', fromPos: 'v.', toPos: 'adj.', answer: 'trusting', meaning: '信任的', example: { en: 'A trusting smile.', cn: '一个信任的微笑。' }, unit: 'U4' },
  { from: 'curiosity', fromPos: 'n.', toPos: 'adj.', answer: 'curious', meaning: '好奇的', example: { en: 'The boy is curious.', cn: '那个男孩很好奇。' }, unit: 'U1' },
  { from: 'curious', fromPos: 'adj.', toPos: 'adv.', answer: 'curiously', meaning: '好奇地', example: { en: 'She looked at him curiously.', cn: '她好奇地看着他。' }, unit: 'U1' },
  { from: 'knowledge', fromPos: 'n.', toPos: 'adj.', answer: 'knowledgeable', meaning: '知识渊博的', example: { en: 'He is knowledgeable.', cn: '他知识渊博。' }, unit: 'U4' },
  { from: 'communicate', fromPos: 'v.', toPos: 'n.', answer: 'communication', meaning: '交流；沟通', example: { en: 'Good communication is key.', cn: '良好的沟通是关键。' }, unit: 'U4' },
  { from: 'method', fromPos: 'n.', toPos: 'n.-pl', answer: 'methods', meaning: '方法（复数）', example: { en: 'Try different methods.', cn: '尝试不同的方法。' }, unit: 'U4' },
  { from: 'kilometer', fromPos: 'n.', toPos: 'n.-pl', answer: 'kilometers', meaning: '公里（复数）', example: { en: 'It is five kilometers away.', cn: '它离这五公里远。' }, unit: 'MIDDLE' },
  { from: 'taste', fromPos: 'v.', toPos: 'adj.', answer: 'tasty', meaning: '美味的', example: { en: 'The soup is tasty.', cn: '这汤很好喝。' }, unit: 'U4' },
  { from: 'fresh', fromPos: 'adj.', toPos: 'adj.(比较级)', answer: 'fresher', meaning: '更新鲜的（比较级）', example: { en: 'The bread is fresher.', cn: '这面包更新鲜。' }, unit: 'MIDDLE' },
  { from: 'customer', fromPos: 'n.', toPos: 'n.-pl', answer: 'customers', meaning: '顾客（复数）', example: { en: 'The shop has many customers.', cn: '这家店有很多顾客。' }, unit: 'U4' },
  { from: 'secret', fromPos: 'n.', toPos: 'n.-pl', answer: 'secrets', meaning: '秘密（复数）', example: { en: 'She keeps secrets.', cn: '她保守秘密。' }, unit: 'MIDDLE' },
  { from: 'cloud', fromPos: 'n.', toPos: 'adj.', answer: 'cloudy', meaning: '多云的', example: { en: 'It is cloudy today.', cn: '今天多云。' }, unit: 'MIDDLE' },
  { from: 'greet', fromPos: 'v.', toPos: 'n.', answer: 'greeting', meaning: '问候；招呼', example: { en: 'He gave a warm greeting.', cn: '他热情地打了招呼。' }, unit: 'U4' },
  { from: 'exact', fromPos: 'adj.', toPos: 'adv.', answer: 'exactly', meaning: '精确地', example: { en: 'That is exactly right.', cn: '那完全正确。' }, unit: 'MIDDLE' },
  { from: 'train', fromPos: 'v.', toPos: 'n.', answer: 'training', meaning: '训练', example: { en: 'He needs more training.', cn: '他需要更多训练。' }, unit: 'U4' },
  { from: 'cook', fromPos: 'v.', toPos: 'n.', answer: 'cooking', meaning: '烹饪', example: { en: 'Cooking is fun.', cn: '烹饪很有趣。' }, unit: 'U4' },
  { from: 'join', fromPos: 'v.', toPos: 'n.', answer: 'joining', meaning: '加入；参加', example: { en: 'Joining the club is great.', cn: '加入俱乐部很棒。' }, unit: 'U1' },
  { from: 'support', fromPos: 'v.', toPos: 'adj.', answer: 'supporting', meaning: '支持的', example: { en: 'A supporting role.', cn: '一个支持的角色。' }, unit: 'MIDDLE' },
  { from: 'study', fromPos: 'v.', toPos: 'v.-ed', answer: 'studied', meaning: '学习（过去式）', example: { en: 'He studied hard.', cn: '他努力学习。' }, unit: 'MIDDLE' },
  { from: 'pick', fromPos: 'v.', toPos: 'v.-ed', answer: 'picked', meaning: '摘（过去式）', example: { en: 'She picked flowers.', cn: '她摘了花。' }, unit: 'MIDDLE' },
  { from: 'forbid', fromPos: 'v.', toPos: 'adj.', answer: 'forbidden', meaning: '被禁止的', example: { en: 'Smoking is forbidden.', cn: '禁止吸烟。' }, unit: 'MIDDLE' },
  { from: 'tasty', fromPos: 'adj.', toPos: 'adj.(比较级)', answer: 'tastier', meaning: '更美味的（比较级）', example: { en: 'This one is tastier.', cn: '这个更好吃。' }, unit: 'U4' },
  { from: 'travel', fromPos: 'v.', toPos: 'n.', answer: 'traveling', meaning: '旅行', example: { en: 'Traveling broadens the mind.', cn: '旅行开阔眼界。' }, unit: 'U4' },
  { from: 'encourage', fromPos: 'v.', toPos: 'adj.', answer: 'encouraging', meaning: '令人鼓舞的', example: { en: 'That is encouraging news.', cn: '那是令人鼓舞的消息。' }, unit: 'MIDDLE' },
  { from: 'rise', fromPos: 'v.', toPos: 'v.-pp', answer: 'risen', meaning: '升起（过去分词）', example: { en: 'The sun has risen.', cn: '太阳已经升起。' }, unit: 'MIDDLE' },
  { from: 'free', fromPos: 'adj.', toPos: 'adj.(比较级)', answer: 'freer', meaning: '更自由的（比较级）', example: { en: 'The internet makes life freer.', cn: '互联网让生活更自由。' }, unit: 'MIDDLE' },
];