// 不规则动词词库（中考高频 ~80 个）
// 字段：base 原形 / past 过去式 / participle 过去分词 / meaning 中文 / example 例句
// 独立于课本单元，供「听写 · 不规则动词」模式使用。
window.IRREGULAR_VERBS = [
  { base: 'be', past: 'was/were', participle: 'been', meaning: '是；在', example: { en: 'He was happy yesterday.', cn: '他昨天很开心。' } },
  { base: 'have', past: 'had', participle: 'had', meaning: '有', example: { en: 'She had a cat.', cn: '她曾经有一只猫。' } },
  { base: 'do', past: 'did', participle: 'done', meaning: '做', example: { en: 'He did his homework.', cn: '他做了作业。' } },
  { base: 'go', past: 'went', participle: 'gone', meaning: '去', example: { en: 'They went to the park.', cn: '他们去公园了。' } },
  { base: 'come', past: 'came', participle: 'come', meaning: '来', example: { en: 'She came home late.', cn: '她很晚才回家。' } },
  { base: 'see', past: 'saw', participle: 'seen', meaning: '看见', example: { en: 'I saw a dog.', cn: '我看见一只狗。' } },
  { base: 'eat', past: 'ate', participle: 'eaten', meaning: '吃', example: { en: 'He ate an apple.', cn: '他吃了一个苹果。' } },
  { base: 'take', past: 'took', participle: 'taken', meaning: '拿；花费', example: { en: 'She took my book.', cn: '她拿走了我的书。' } },
  { base: 'make', past: 'made', participle: 'made', meaning: '制作；使', example: { en: 'He made a cake.', cn: '他做了一个蛋糕。' } },
  { base: 'get', past: 'got', participle: 'got/gotten', meaning: '得到；变得', example: { en: 'I got a gift.', cn: '我得到了一份礼物。' } },
  { base: 'give', past: 'gave', participle: 'given', meaning: '给', example: { en: 'He gave me a pen.', cn: '他给了我一支笔。' } },
  { base: 'write', past: 'wrote', participle: 'written', meaning: '写', example: { en: 'She wrote a letter.', cn: '她写了一封信。' } },
  { base: 'speak', past: 'spoke', participle: 'spoken', meaning: '说（语言）', example: { en: 'He spoke English.', cn: '他说了英语。' } },
  { base: 'break', past: 'broke', participle: 'broken', meaning: '打破', example: { en: 'He broke the cup.', cn: '他打碎了杯子。' } },
  { base: 'choose', past: 'chose', participle: 'chosen', meaning: '选择', example: { en: 'She chose a red one.', cn: '她选了红色的。' } },
  { base: 'drive', past: 'drove', participle: 'driven', meaning: '驾驶', example: { en: 'He drove a car.', cn: '他开了一辆车。' } },
  { base: 'fall', past: 'fell', participle: 'fallen', meaning: '掉落', example: { en: 'The book fell down.', cn: '书掉下来了。' } },
  { base: 'fly', past: 'flew', participle: 'flown', meaning: '飞', example: { en: 'A bird flew away.', cn: '一只鸟飞走了。' } },
  { base: 'forget', past: 'forgot', participle: 'forgotten', meaning: '忘记', example: { en: 'I forgot my bag.', cn: '我忘了我的包。' } },
  { base: 'freeze', past: 'froze', participle: 'frozen', meaning: '冻结', example: { en: 'The lake froze.', cn: '湖面结冰了。' } },
  { base: 'grow', past: 'grew', participle: 'grown', meaning: '生长；种植', example: { en: 'The plant grew fast.', cn: '植物长得很快。' } },
  { base: 'hide', past: 'hid', participle: 'hidden', meaning: '隐藏', example: { en: 'He hid behind the door.', cn: '他藏在门后。' } },
  { base: 'know', past: 'knew', participle: 'known', meaning: '知道', example: { en: 'I knew the answer.', cn: '我知道答案。' } },
  { base: 'ride', past: 'rode', participle: 'ridden', meaning: '骑', example: { en: 'She rode a bike.', cn: '她骑了自行车。' } },
  { base: 'ring', past: 'rang', participle: 'rung', meaning: '响铃', example: { en: 'The bell rang.', cn: '铃响了。' } },
  { base: 'rise', past: 'rose', participle: 'risen', meaning: '升起；起床', example: { en: 'The sun rose early.', cn: '太阳早早升起。' } },
  { base: 'run', past: 'ran', participle: 'run', meaning: '跑', example: { en: 'He ran to school.', cn: '他跑去了学校。' } },
  { base: 'sing', past: 'sang', participle: 'sung', meaning: '唱', example: { en: 'She sang a song.', cn: '她唱了一首歌。' } },
  { base: 'sink', past: 'sank', participle: 'sunk', meaning: '下沉', example: { en: 'The ship sank.', cn: '船沉了。' } },
  { base: 'sit', past: 'sat', participle: 'sat', meaning: '坐', example: { en: 'He sat on the chair.', cn: '他坐在椅子上。' } },
  { base: 'sleep', past: 'slept', participle: 'slept', meaning: '睡觉', example: { en: 'The baby slept.', cn: '宝宝睡着了。' } },
  { base: 'steal', past: 'stole', participle: 'stolen', meaning: '偷', example: { en: 'Someone stole my bike.', cn: '有人偷了我的自行车。' } },
  { base: 'swim', past: 'swam', participle: 'swum', meaning: '游泳', example: { en: 'He swam in the lake.', cn: '他在湖里游泳。' } },
  { base: 'throw', past: 'threw', participle: 'thrown', meaning: '扔', example: { en: 'He threw the ball.', cn: '他扔出了球。' } },
  { base: 'wear', past: 'wore', participle: 'worn', meaning: '穿', example: { en: 'She wore a red dress.', cn: '她穿了一条红裙子。' } },
  { base: 'win', past: 'won', participle: 'won', meaning: '赢', example: { en: 'Our team won the game.', cn: '我们队赢了比赛。' } },
  { base: 'catch', past: 'caught', participle: 'caught', meaning: '抓住；赶上', example: { en: 'He caught the ball.', cn: '他接住了球。' } },
  { base: 'teach', past: 'taught', participle: 'taught', meaning: '教', example: { en: 'She taught us math.', cn: '她教我们数学。' } },
  { base: 'buy', past: 'bought', participle: 'bought', meaning: '买', example: { en: 'I bought a book.', cn: '我买了一本书。' } },
  { base: 'bring', past: 'brought', participle: 'brought', meaning: '带来', example: { en: 'He brought his friend.', cn: '他带来了他的朋友。' } },
  { base: 'think', past: 'thought', participle: 'thought', meaning: '想；认为', example: { en: 'I thought about it.', cn: '我想过这件事。' } },
  { base: 'fight', past: 'fought', participle: 'fought', meaning: '打架；战斗', example: { en: 'They fought bravely.', cn: '他们英勇战斗。' } },
  { base: 'find', past: 'found', participle: 'found', meaning: '找到', example: { en: 'She found her key.', cn: '她找到了钥匙。' } },
  { base: 'hold', past: 'held', participle: 'held', meaning: '握住；举行', example: { en: 'He held my hand.', cn: '他握住我的手。' } },
  { base: 'keep', past: 'kept', participle: 'kept', meaning: '保持；饲养', example: { en: 'She kept a diary.', cn: '她写日记。' } },
  { base: 'leave', past: 'left', participle: 'left', meaning: '离开；留下', example: { en: 'He left the room.', cn: '他离开了房间。' } },
  { base: 'lend', past: 'lent', participle: 'lent', meaning: '借出', example: { en: 'She lent me a pen.', cn: '她借给我一支笔。' } },
  { base: 'meet', past: 'met', participle: 'met', meaning: '遇见', example: { en: 'I met a friend.', cn: '我遇见了一个朋友。' } },
  { base: 'pay', past: 'paid', participle: 'paid', meaning: '支付', example: { en: 'He paid the bill.', cn: '他付了账单。' } },
  { base: 'say', past: 'said', participle: 'said', meaning: '说', example: { en: 'She said goodbye.', cn: '她说再见。' } },
  { base: 'sell', past: 'sold', participle: 'sold', meaning: '卖', example: { en: 'He sold his bike.', cn: '他卖掉了自行车。' } },
  { base: 'send', past: 'sent', participle: 'sent', meaning: '送；寄', example: { en: 'She sent a letter.', cn: '她寄了一封信。' } },
  { base: 'shut', past: 'shut', participle: 'shut', meaning: '关闭', example: { en: 'He shut the door.', cn: '他关上了门。' } },
  { base: 'spend', past: 'spent', participle: 'spent', meaning: '花费；度过', example: { en: 'I spent ten yuan.', cn: '我花了十元。' } },
  { base: 'stand', past: 'stood', participle: 'stood', meaning: '站立；忍受', example: { en: 'He stood by the window.', cn: '他站在窗边。' } },
  { base: 'tell', past: 'told', participle: 'told', meaning: '告诉', example: { en: 'She told a story.', cn: '她讲了一个故事。' } },
  { base: 'understand', past: 'understood', participle: 'understood', meaning: '理解', example: { en: 'I understood the lesson.', cn: '我听懂了课。' } },
  { base: 'wake', past: 'woke', participle: 'woken', meaning: '醒来', example: { en: 'He woke up early.', cn: '他很早就醒了。' } },
  { base: 'beat', past: 'beat', participle: 'beaten', meaning: '打败；敲击', example: { en: 'We beat their team.', cn: '我们打败了他们队。' } },
  { base: 'blow', past: 'blew', participle: 'blown', meaning: '吹', example: { en: 'The wind blew hard.', cn: '风刮得很大。' } },
  { base: 'draw', past: 'drew', participle: 'drawn', meaning: '画；拉', example: { en: 'She drew a cat.', cn: '她画了一只猫。' } },
  { base: 'drink', past: 'drank', participle: 'drunk', meaning: '喝', example: { en: 'He drank some water.', cn: '他喝了一些水。' } },
  { base: 'dream', past: 'dreamt', participle: 'dreamt', meaning: '做梦', example: { en: 'She dreamt of a trip.', cn: '她梦到了一次旅行。' } },
  { base: 'feed', past: 'fed', participle: 'fed', meaning: '喂养', example: { en: 'He fed the cat.', cn: '他喂了猫。' } },
  { base: 'feel', past: 'felt', participle: 'felt', meaning: '感觉', example: { en: 'I felt happy.', cn: '我感到开心。' } },
  { base: 'hang', past: 'hung', participle: 'hung', meaning: '悬挂', example: { en: 'He hung a picture.', cn: '他挂了一幅画。' } },
  { base: 'hear', past: 'heard', participle: 'heard', meaning: '听见', example: { en: 'I heard a song.', cn: '我听见一首歌。' } },
  { base: 'hit', past: 'hit', participle: 'hit', meaning: '撞击；打', example: { en: 'He hit the ball.', cn: '他击打了球。' } },
  { base: 'hurt', past: 'hurt', participle: 'hurt', meaning: '伤害；疼痛', example: { en: 'He hurt his leg.', cn: '他伤了腿。' } },
  { base: 'learn', past: 'learnt', participle: 'learnt', meaning: '学习', example: { en: 'She learnt English.', cn: '她学了英语。' } },
  { base: 'lose', past: 'lost', participle: 'lost', meaning: '丢失；输', example: { en: 'I lost my key.', cn: '我丢了钥匙。' } },
  { base: 'read', past: 'read', participle: 'read', meaning: '读', example: { en: 'He read a book.', cn: '他读了一本书。' } },
  { base: 'put', past: 'put', participle: 'put', meaning: '放；放置', example: { en: 'She put it on the table.', cn: '她把它放在桌上。' } },
  { base: 'set', past: 'set', participle: 'set', meaning: '设置；放', example: { en: 'He set the table.', cn: '他摆好了餐具。' } },
  { base: 'let', past: 'let', participle: 'let', meaning: '让；允许', example: { en: 'Let me help you.', cn: '让我帮你。' } },
  { base: 'build', past: 'built', participle: 'built', meaning: '建造', example: { en: 'They built a house.', cn: '他们建了一栋房子。' } },
  { base: 'burn', past: 'burnt', participle: 'burnt', meaning: '燃烧', example: { en: 'The fire burnt out.', cn: '火熄灭了。' } },
  { base: 'dig', past: 'dug', participle: 'dug', meaning: '挖', example: { en: 'He dug a hole.', cn: '他挖了一个洞。' } },
  { base: 'cut', past: 'cut', participle: 'cut', meaning: '切；剪', example: { en: 'She cut the paper.', cn: '她剪了纸。' } },
  { base: 'light', past: 'lit', participle: 'lit', meaning: '点燃；照亮', example: { en: 'He lit a candle.', cn: '他点了一根蜡烛。' } }
];
